SportsStore2013/SportsStore.Web.UI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Core.Contracts;
using SportsStore.Core.Contracts.Models;
using SportsStore.Web.UI.Models;

namespace SportsStore.Web.UI.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductCore _products;

        public CartController(IProductCore products)
        {
            _products = products;
        }

        public ActionResult Index(Cart cart, string returnUrl)
        {
            var viewModel = new CartIndexViewModel
                                {
                                    Cart = cart,
                                    ReturnUrl = returnUrl
                                };

            return View(viewModel);
        }

        public RedirectToRouteResult AddToCart(Cart cart, int id, int quantity, string returnUrl)
        {
            Product product = _products.GetProductById(id);

            if(product != null)
                cart.AddItem(product, quantity);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int id, string returnUrl)
        {
            Product product = _products.GetProductById(id);

            if(product != null)
                cart.RemoveLine(product);

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }


        public ActionResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if(!cart.Lines.Any())
                ModelState.AddModelError(string.Empty, "Sorry, your cart is empty");

            if (!ModelState.IsValid)
                return View(shippingDetails);

            // If we got this far, order is ready to be processed.
            _products.ProcessOrder(cart, shippingDetails);
            cart.Clear();
            return View("Completed");
        }
    }
}

SportsStore2013/SportsStore.Web.UI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Core.Contracts;

namespace SportsStore.Web.UI.Controllers
{
    public class NavController : Controller
    {
        private readonly ICategoryCore _categories;

        public NavController(ICategoryCore categories)
        {
            _categories = categories;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _categories.GetCategoryNames();

            return PartialView(categories);
        }

        public PartialViewResult AdminMenu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _categories.GetCategoryNames();

            return PartialView(categories);
        }
    }
}

SportsStore2013/SportsStore.Web.UI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }

        .sidebar-nav {
            padding: 9px 0;
        }
    </style>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <section class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="#">Sports Store</a>
                <div class="nav-collapse collapse">
                    <p class="navbar-text pull-right">
                        @*Logged in as <a href="#" class="navbar-link">Username</a>*@
                    </p>
                    <ul class="nav">
                        @*                            <li class="active"><a href="#">Home</a></li>
                            <li class="active"><a href="#">Home</a></li>
                            <li class="active"><a href="#">Home</a></li>*@
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    @{Html.RenderAction("AdminMenu", "Nav");}
                </div>
            </div>
            <div class="span9">
                <div class="well well-small">
                    <!-- Search bar -->
                    <form class="form-search">
                        
                        <input type="text" class="input-medium search-query" placeholder="Search Products"/>
                        <button type="submit" class="btn">Search</button>
                    </form>

                </div>
                @RenderBody()
            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
    
    <div>
        @*@if (TempData["message"] != null)
        {
            <script>
                toastr.success('@TempData["message"]')
            </script>
        }*@
        
        @Dialog.ShowToast(TempData)
    </div>
    
   @* <script>
        $(function() {
            toastr.options.positionClass = "toast-bottom-right";
        })
    </script>*@
</body>
</html>

SportsStore2013/SportsStore.Web.UI/Views/Shared/_CacheWarningModal.cshtml
<div id="cacheWarning" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 id="modalLabel">Refresh Cache</h3>
    </div>
    <div class="modal-body">
        This will cause all the products to be reloaded from the database. Only proceed if you're 100% sure!
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        @Html.ActionLink("Proceed", "RefreshCache", new { category = Model.CurrentCategory }, new { @class = "btn btn-primary" })
    </div>
</div>

SportsStore2013/SportsStore.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }

        .sidebar-nav {
            padding: 9px 0;
        }
    </style>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <section class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="#">Sports Store</a>
                <div class="nav-collapse collapse">
                    <p class="navbar-text pull-right">
                        @*Logged in as <a href="#" class="navbar-link">Username</a>*@
                    </p>
                    <ul class="nav">
                        @*                            <li class="active"><a href="#">Home</a></li>
                            <li class="active"><a href="#">Home</a></li>
                            <li class="active"><a href="#">Home</a></li>*@
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    @* <ul class="nav nav-list">
                            <li class="nav-header">All Categories</li>
                            <li class="active"><a href="#">Category 1</a></li>
                            <li><a href="#">Category 2</a></li>
                        </ul>*@

                    @{Html.RenderAction("Menu", "Nav");}
                </div>
            </div>
            <div class="span9">
                <div class="well well-small">
                    <!-- Search bar -->
                    <form class="form-search">
                        
                        <input type="text" class="input-medium search-query" placeholder="Search Products"/>
                        <button type="submit" class="btn">Search</button>
                        <span class="pull-right">@{ Html.RenderAction("Summary", "Cart");}</span>
                    </form>

                </div>
                @RenderBody()
            </div>
        </div>
    </section>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>