SportsStore2013/SportsStore.Web.UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Core.Contracts;
using SportsStore.Core.Contracts.Models;
using SportsStore.Web.UI.Models;
using SportsStore.Web.UI.Extensions;

namespace SportsStore.Web.UI.Controllers
{
    public class AdminController : BaseProductController
    {
        private readonly ICategoryCore _categories;

        public AdminController(IProductCore products, ICategoryCore categories)
            : base(products, pageSize: 10)
        {
            _categories = categories;
        }

        public ActionResult Edit(int id, string returnUrl)
        {
            Product product = _products.GetProductById(id);

            IList<Category> allCategories = _categories.GetAllCategories();

            var viewModel = new ProductEditViewModel
                                {
                                    Product = product,
                                    Categories = allCategories,
                                    ReturnUrl = returnUrl
                                };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(ProductEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                _products.Save(model.Product)
                         .Commit();

                TempData.AddMessage(MessageType.Success, string.Format("{0} has been saved", model.Product.Name));

                return RedirectToAction("List", new { category = (string)null });
            }
            
            //  there is something wrong with the data values
            return View(model);
        }

        public ActionResult Create(string returnUrl)
        {
            IList<Category> categories = _categories.GetAllCategories();
            var viewModel = new ProductEditViewModel { Product = new Product(), Categories = categories, ReturnUrl = returnUrl };
            return View("Edit", viewModel);
        }


        public ActionResult RefreshCache(string category)
        {
            _products.RefreshProductCache();
            return RedirectToAction("List", new { category });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Contract.Requires<ArgumentException>(id > 0, "Invalid productId");

            _products.Delete(id).Commit();

            return RedirectToAction("List", new { category = (string)null });
        }
    }
}

SportsStore2013/SportsStore.Web.UI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Core.Contracts;

namespace SportsStore.Web.UI.Controllers
{
    public class NavController : Controller
    {
        private readonly ICategoryCore _categories;

        public NavController(ICategoryCore categories)
        {
            _categories = categories;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _categories.GetCategoryNames();

            return PartialView(categories);
        }

        public PartialViewResult AdminMenu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = _categories.GetCategoryNames();

            return PartialView(categories);
        }
    }
}

SportsStore2013/SportsStore.Web.UI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Core.Contracts;
using SportsStore.Core.Contracts.Models;
using SportsStore.Web.UI.Models;

namespace SportsStore.Web.UI.Controllers
{
    public class ProductController : BaseProductController
    {
        public ProductController(IProductCore products)
            : base(products)
        {
        }

        public ActionResult Details(int id, string returnUrl)
        {
            Product product = _products.GetProductById(id);

            ProductDetail viewModel = new ProductDetail(product);

            ViewBag.ReturnUrl = returnUrl;

            return View(viewModel);
        }

    }
}

SportsStore2013/SportsStore.Web.UI/Views/Nav/AdminMenu.cshtml
@model IEnumerable<string>

<ul class="nav nav-list">
    <li class="nav-header">@Html.ActionLink("Home", "List", "Admin")</li>
    
    @foreach (var link in Model)
    {
        <li class="@(link == ViewBag.SelectedCategory ? "active" : null)">
            @Html.RouteLink(link, new
                                      {
                                          controller = "Admin",
                                          action = "List",
                                          category = link
                                      })
        </li>
    }

</ul>

SportsStore2013/SportsStore.Web.UI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

<ul class="nav nav-list">
    <li class="nav-header">@Html.ActionLink("Home", "List", "Product")</li>
    
    @foreach (var link in Model)
    {
        <li class="@(link == ViewBag.SelectedCategory ? "active" : null)">
            @Html.RouteLink(link, new
                                      {
                                          controller = "Product",
                                          action = "List",
                                          category = link
                                      })
        </li>
    }

</ul>